### ISSUE TITLE
Won't run with winston error

### ISSUE THREAD

**Issue by polymathuk** [pavben/WebIRC#31]
debian 11
Followed the install instructions. Got this:

```
> WebIRC@0.0.1 start /home/dave/WebIRC
> babel-node main.js

Failed to start WebIRC Error: { colors, emitErrs, formatters, padLevels, rewriters, stripColors } were removed in winston@3.0.0.
Use a custom winston.format(function) instead.
See: https://github.com/winstonjs/winston/tree/master/UPGRADE-3.0.md
    at DerivedLogger.configure (/home/dave/WebIRC/node_modules/winston/lib/winston/logger.js:135:13)
    at new Logger (/home/dave/WebIRC/node_modules/winston/lib/winston/logger.js:42:10)
    at new DerivedLogger (/home/dave/WebIRC/node_modules/winston/lib/winston/create-logger.js:44:7)
    at Object.module.exports [as createLogger] (/home/dave/WebIRC/node_modules/winston/lib/winston/create-logger.js:48:18)
    at Object.init (/home/dave/WebIRC/logger.js:35:19)
    at Function.<anonymous> (/home/dave/WebIRC/main.js:32:10)
    at AsyncBlock.runIfSatisfied (/home/dave/WebIRC/async.js:242:25)
    at AsyncBlock.depProvided (/home/dave/WebIRC/async.js:202:10)
    at /home/dave/WebIRC/async.js:111:18
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WebIRC@0.0.1 start: `babel-node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WebIRC@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-23T19_37_33_227Z-debug.log
```

What should I do?

**Comment by pavben** [comment]
It's been many years since I've tried running WebIRC. It might only work with very old versions of its dependencies, but I don't recommend trying to figure it out unless you're very passionate about it. I'm not actively supporting it, so I'll probably archive the repository soon.

**Comment by polymathuk** [comment]
Thanks for the very honest update. 
I may attempt downgrading the version of winston to see if that fixes this immediate error, but if there are more problems then I will abandon the idea. Thanks again.

**Comment by polymathuk** [comment]
Just for completeness, I ran two bash commands in the WebIRC directory and this fixed the winston dependency problem:
`npm install winston@2.4.7`
`npm remove winston@3.8.2`
